name: DiscordBridge
version: '@VERSION@'
description: '@DESCRIPTION@'

author: Jacob Gillespie
website: '@URL@'

loadbefore: [SpaceBukkit, RemoteToolkitPlugin]
softdepend: [Multiverse-Core]

main: gg.obsidian.discordbridge.Plugin

permissions:
  discordbridge.reload:
    description: Reload the Discord Bridge
    default: op
  discordbridge.cleverbot:
    description: Determines whether this user can talk to Cleverbot
    default: true

commands:
  discord:
    description: Issue a command to the bot
    usage: /discord <command>
  marina:
    description: Chat with Marina!
    usage: /marina <what to say to Marina>