name: DiscordBridge
version: '@VERSION@'
description: '@DESCRIPTION@'

author: Jacob Gillespie
website: '@URL@'

loadbefore: [SpaceBukkit, RemoteToolkitPlugin]

main: gg.obsidian.discordbridge.Plugin

permissions:
  discordbridge.reload:
    description: Reload the Discord Bridge
    default: op

commands:
  discord:
    description: Issue a command to the bot
    usage: /discord <command>